---
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  - binary: go-tpc
    id: go-tpc
    main: ./cmd/go-tpc/
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
    mod_timestamp: '{{ .CommitTimestamp }}'
    targets:
      - linux_amd64_v1
      - linux_arm64_v1
      - darwin_amd64_v1
      - darwin_arm64_v1

archives:
  - files:
    - none*
    wrap_in_directory: false

checksum:
  name_template: 'checksums.txt'
